- hosts: default
  tasks:
    - name: Install APT dependencies
      become: true
      apt:
        name: '{{item}}'
      with_items:
        - nodejs
        - nodejs-legacy
        - npm

    - name: Install npm dependencies
      npm:
        name: '{{item}}'
      with_items:
        - express
        - mongoose
        - react
        - react-dom
        - webpack
        - babel-core
        - babel-loader
        - babel-preset-es2015
        - babel-preset-react
  
    - name: Install global npm dependencies
      npm:
        name: '{{item}}'
        global: true
      with_items:
        - nodemon