- hosts: default
  tasks:
    - name: Install APT dependencies
      become: true
      apt:
        name: '{{item}}'
      with_items:
        - nodejs
        - nodejs-legacy
        - npm

    - name: Install npm dependencies
      npm:
        path: /vagrant
